"use client";

import {
  LineChart,
  Line,
  BarChart,
  Bar,
  PieChart,
  Pie,
  Cell,
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
} from "recharts";

export interface ReportSection {
  id: string;
  type: string;
  title: string;
  narrative: string;
  keyMetrics: { label: string; value: string; change: number; trend: "up" | "down" | "neutral" }[];
  insights: { type: "win" | "concern" | "recommendation"; text: string }[];
  chartData?: {
    type: "line" | "bar" | "pie" | "area";
    data: Record<string, unknown>[];
    xKey: string;
    yKey: string | string[];
  };
}

const CHART_COLORS = ["#3475EF", "#10B981", "#F59E0B", "#EF4444", "#8B5CF6"];

export function ReportView({
  brandColor,
  workspaceName,
  workspaceLogoUrl,
  clientName,
  title,
  dateRangeStart,
  dateRangeEnd,
  sections,
}: {
  brandColor: string;
  workspaceName: string;
  workspaceLogoUrl: string | null;
  clientName: string;
  title: string;
  dateRangeStart: string;
  dateRangeEnd: string;
  sections: ReportSection[];
}) {
  const safeSections = Array.isArray(sections) ? sections : [];
  return (
    <div className="bg-white text-slate-900" style={{ ["--brand" as string]: brandColor }}>
      <header
        className="px-12 py-10 border-b-4"
        style={{ borderColor: brandColor, backgroundColor: `${brandColor}0a` }}
      >
        <div className="flex items-center justify-between">
          <div>
            {workspaceLogoUrl ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img src={workspaceLogoUrl} alt={workspaceName} className="h-10 mb-4" />
            ) : (
              <p className="text-sm font-bold uppercase tracking-wider" style={{ color: brandColor }}>
                {workspaceName}
              </p>
            )}
            <h1 className="text-4xl font-bold mt-2">{title}</h1>
            <p className="text-slate-600 mt-1">
              {clientName} · {dateRangeStart} – {dateRangeEnd}
            </p>
          </div>
        </div>
      </header>

      <main className="px-12 py-10 space-y-12">
        {safeSections.map((section, i) => (
          <Section key={section.id ?? i} section={section} brandColor={brandColor} />
        ))}
      </main>

      <footer className="px-12 py-6 border-t border-slate-200 text-xs text-slate-500">
        Generated by Reportly · {workspaceName}
      </footer>
    </div>
  );
}

function Section({ section, brandColor }: { section: ReportSection; brandColor: string }) {
  const keyMetrics = Array.isArray(section.keyMetrics) ? section.keyMetrics : [];
  const insights = Array.isArray(section.insights) ? section.insights : [];

  return (
    <section>
      <h2 className="text-2xl font-bold mb-2" style={{ color: brandColor }}>
        {section.title ?? ""}
      </h2>
      <div className="prose prose-sm max-w-none mb-6 whitespace-pre-wrap text-slate-700">
        {section.narrative ?? ""}
      </div>

      {keyMetrics.length > 0 && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
          {keyMetrics.map((m, i) => (
            <div key={i} className="rounded-2xl border border-slate-200 p-4 bg-slate-50">
              <p className="text-[10px] font-bold uppercase tracking-widest text-slate-500">{m.label}</p>
              <p className="text-2xl font-bold mt-1">{m.value}</p>
              <p
                className={`text-xs font-bold mt-1 ${
                  m.trend === "up" ? "text-emerald-600" : m.trend === "down" ? "text-red-600" : "text-slate-500"
                }`}
              >
                {(m.change ?? 0) > 0 ? "▲" : (m.change ?? 0) < 0 ? "▼" : "—"}{" "}
                {Math.abs(m.change ?? 0).toFixed(1)}%
              </p>
            </div>
          ))}
        </div>
      )}

      {section.chartData && Array.isArray(section.chartData.data) && section.chartData.data.length > 0 && (
        <Chart config={section.chartData} brandColor={brandColor} />
      )}

      {insights.length > 0 && (
        <div className="mt-6 space-y-2">
          {insights.map((ins, i) => (
            <div
              key={i}
              className={`rounded-xl p-4 text-sm ${
                ins.type === "win"
                  ? "bg-emerald-50 text-emerald-900"
                  : ins.type === "concern"
                    ? "bg-amber-50 text-amber-900"
                    : "bg-blue-50 text-blue-900"
              }`}
            >
              <span className="font-bold uppercase text-[10px] tracking-widest mr-2">{ins.type}</span>
              {ins.text}
            </div>
          ))}
        </div>
      )}
    </section>
  );
}

function Chart({ config, brandColor }: { config: NonNullable<ReportSection["chartData"]>; brandColor: string }) {
  // Defensive: ensure data is a valid array
  const data = Array.isArray(config.data) ? config.data : [];
  if (data.length === 0) return null;

  // Handle both yKey and yKeys (Claude sometimes returns yKeys plural)
  const rawYKey = config.yKey ?? (config as unknown as { yKeys?: string | string[] }).yKeys;
  const yKeys = (Array.isArray(rawYKey) ? rawYKey : rawYKey ? [rawYKey] : ["value"]).filter(Boolean);
  if (yKeys.length === 0) return null;

  const chartType = config.type;

  return (
    <div className="h-64 mt-2 mb-6 border border-slate-200 rounded-2xl p-4 bg-white">
      <ResponsiveContainer width="100%" height="100%">
        {chartType === "pie" ? (
          <PieChart>
            <Pie data={data} dataKey={yKeys[0]} nameKey={config.xKey} cx="50%" cy="50%" outerRadius={80} label>
              {data.map((_, i) => (
                <Cell key={i} fill={CHART_COLORS[i % CHART_COLORS.length]} />
              ))}
            </Pie>
            <Tooltip />
          </PieChart>
        ) : chartType === "bar" ? (
          <BarChart data={data}>
            <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
            <XAxis dataKey={config.xKey} fontSize={10} />
            <YAxis fontSize={10} />
            <Tooltip />
            <Legend />
            {yKeys.map((k, i) => (
              <Bar key={k} dataKey={k} fill={i === 0 ? brandColor : CHART_COLORS[i % CHART_COLORS.length]} />
            ))}
          </BarChart>
        ) : chartType === "area" ? (
          <AreaChart data={data}>
            <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
            <XAxis dataKey={config.xKey} fontSize={10} />
            <YAxis fontSize={10} />
            <Tooltip />
            <Legend />
            {yKeys.map((k, i) => (
              <Area
                key={k}
                type="monotone"
                dataKey={k}
                stroke={i === 0 ? brandColor : CHART_COLORS[i % CHART_COLORS.length]}
                fill={i === 0 ? brandColor : CHART_COLORS[i % CHART_COLORS.length]}
                fillOpacity={0.2}
              />
            ))}
          </AreaChart>
        ) : (
          <LineChart data={data}>
            <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
            <XAxis dataKey={config.xKey} fontSize={10} />
            <YAxis fontSize={10} />
            <Tooltip />
            <Legend />
            {yKeys.map((k, i) => (
              <Line
                key={k}
                type="monotone"
                dataKey={k}
                stroke={i === 0 ? brandColor : CHART_COLORS[i % CHART_COLORS.length]}
                strokeWidth={2}
                dot={false}
              />
            ))}
          </LineChart>
        )}
      </ResponsiveContainer>
    </div>
  );
}
